/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.devopsicon.kafka.consumer.mongo;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Sale extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4405661322030053170L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Sale\",\"namespace\":\"org.devopsicon.kafka.consumer.mongo\",\"fields\":[{\"name\":\"amount\",\"type\":\"float\",\"doc\":\"Total Amount of Sale\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Sale> ENCODER =
      new BinaryMessageEncoder<Sale>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Sale> DECODER =
      new BinaryMessageDecoder<Sale>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Sale> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Sale> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Sale>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Sale to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Sale from a ByteBuffer. */
  public static Sale fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Total Amount of Sale */
  @Deprecated public float amount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Sale() {}

  /**
   * All-args constructor.
   * @param amount Total Amount of Sale
   */
  public Sale(java.lang.Float amount) {
    this.amount = amount;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return amount;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: amount = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'amount' field.
   * @return Total Amount of Sale
   */
  public java.lang.Float getAmount() {
    return amount;
  }

  /**
   * Sets the value of the 'amount' field.
   * Total Amount of Sale
   * @param value the value to set.
   */
  public void setAmount(java.lang.Float value) {
    this.amount = value;
  }

  /**
   * Creates a new Sale RecordBuilder.
   * @return A new Sale RecordBuilder
   */
  public static org.devopsicon.kafka.consumer.mongo.Sale.Builder newBuilder() {
    return new org.devopsicon.kafka.consumer.mongo.Sale.Builder();
  }

  /**
   * Creates a new Sale RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Sale RecordBuilder
   */
  public static org.devopsicon.kafka.consumer.mongo.Sale.Builder newBuilder(org.devopsicon.kafka.consumer.mongo.Sale.Builder other) {
    return new org.devopsicon.kafka.consumer.mongo.Sale.Builder(other);
  }

  /**
   * Creates a new Sale RecordBuilder by copying an existing Sale instance.
   * @param other The existing instance to copy.
   * @return A new Sale RecordBuilder
   */
  public static org.devopsicon.kafka.consumer.mongo.Sale.Builder newBuilder(org.devopsicon.kafka.consumer.mongo.Sale other) {
    return new org.devopsicon.kafka.consumer.mongo.Sale.Builder(other);
  }

  /**
   * RecordBuilder for Sale instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Sale>
    implements org.apache.avro.data.RecordBuilder<Sale> {

    /** Total Amount of Sale */
    private float amount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.devopsicon.kafka.consumer.mongo.Sale.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.amount)) {
        this.amount = data().deepCopy(fields()[0].schema(), other.amount);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Sale instance
     * @param other The existing instance to copy.
     */
    private Builder(org.devopsicon.kafka.consumer.mongo.Sale other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.amount)) {
        this.amount = data().deepCopy(fields()[0].schema(), other.amount);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'amount' field.
      * Total Amount of Sale
      * @return The value.
      */
    public java.lang.Float getAmount() {
      return amount;
    }

    /**
      * Sets the value of the 'amount' field.
      * Total Amount of Sale
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public org.devopsicon.kafka.consumer.mongo.Sale.Builder setAmount(float value) {
      validate(fields()[0], value);
      this.amount = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * Total Amount of Sale
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'amount' field.
      * Total Amount of Sale
      * @return This builder.
      */
    public org.devopsicon.kafka.consumer.mongo.Sale.Builder clearAmount() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Sale build() {
      try {
        Sale record = new Sale();
        record.amount = fieldSetFlags()[0] ? this.amount : (java.lang.Float) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Sale>
    WRITER$ = (org.apache.avro.io.DatumWriter<Sale>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Sale>
    READER$ = (org.apache.avro.io.DatumReader<Sale>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
